language: php

php:
  - 5.6

matrix:
    allow_failures:
        - php: 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run
